-- Melees
AddTextEntry("WEAPON_KATANA", "Katana")
AddTextEntry("WEAPON_SHIV", "Shiv")
AddTextEntry("WEAPON_SLEDGEHAMMER", "Sledge Hammer")
AddTextEntry("WEAPON_KARAMBIT", "Karambit")
AddTextEntry("WEAPON_KEYBOARD", "Keyboard")
-- GGC Custom Weapons -- Lethals
AddTextEntry("WEAPON_BEANBAG", "Bean Bag")
-- Hand Guns
AddTextEntry("WEAPON_GLOCK17", "Glock-17")
AddTextEntry("WEAPON_GLOCK18C", "Glock-18 Custom")
AddTextEntry("WEAPON_GLOCK22", "Glock-22")
AddTextEntry("WEAPON_DEAGLE", "Desert Eagle")
AddTextEntry("WEAPON_FNX45", "FN FNX45")
AddTextEntry("WEAPON_1911", "1911")
AddTextEntry("WEAPON_GLOCK20", "Glock-20")
AddTextEntry("WEAPON_GLOCK19GEN4", "Glock-19 Gen 4")
AddTextEntry("WEAPON_BROWNING", "BROWNING")
-- SMGs
AddTextEntry("WEAPON_PMXFM", "Beretta PMX")
AddTextEntry("WEAPON_MAC10", "MAC-10")
-- Rifles
AddTextEntry("WEAPON_MK47FM", "Mk47 Mutant")
AddTextEntry("WEAPON_M6IC", "LWRC M6IC")
AddTextEntry("WEAPON_SCARSC", "Scar SC")
AddTextEntry("WEAPON_M4", "M4A1 Carbine")
AddTextEntry("WEAPON_AK47", "AK-47")
AddTextEntry("WEAPON_AK74", "AK-74")
AddTextEntry("WEAPON_AKS74", "AKS-74")
AddTextEntry("WEAPON_GROZA", "OTs-14 Groza")

AddTextEntry("WEAPON_NR_MP5", "MP5")
AddTextEntry("WEAPON_M9", "Beretta M9")
AddTextEntry("WEAPON_P226", "SIG Sauer P226")
AddTextEntry("WEAPON_1911", "Springfield 1911 Mil-Spec")
AddTextEntry("WEAPON_SAUER101", "Hunting Rifle")
AddTextEntry("WEAPON_G17", "GLOCK 17 LE")
AddTextEntry("WEAPON_MAC10", "MAC-10")
AddTextEntry("WEAPON_WALTHER", "Walther P88 Compact")
AddTextEntry("WEAPON_MK18", "MK18")
AddTextEntry("WEAPON_FNFAL", "FN FAL")
AddTextEntry("WEAPON_USP", "H&K USP 45 Auto")
AddTextEntry("WEAPON_MP5", "MP5A3")
AddTextEntry("WEAPON_FM1_M16A4", "M16")
AddTextEntry("WEAPON_P238", "SIG Sauer P238 .380 ACP")
AddTextEntry("WEAPON_FIVESEVEN", "FN Five Seven 5.7x28mm HP")
AddTextEntry("WEAPON_SHANK", "Prison Shank")
AddTextEntry("WEAPON_FLASHBANG", "Flashbang")
AddTextEntry("WEAPON_R700", "Remington 700")
